% Programmer:  James L. Armes
%
% Purpose:  Plots mesh generated by numeric model
function [] = PlotMesh(fileName)

M = CSVREAD(fileName, 1, 0);

x = M(:,2);
y = M(:,3);

plot(x,y, '*k'); xlabel('X Position, m'); ylabel('Y Position, m');


end